models/__init__.py
#!/usr/bin/python3
from models.engine.db_storage import DBStorage

storage = DBStorage()

models/bid.py
from engine import db
from datetime import datetime

class Bidder(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    id_user = db.Column(db.Integer, ForeignKey("userz.id", ondelete='SET NULL'), nullable=True)
    user = relationship("Userz", backref="bids", foreign_keys=[id_user])
    id_dog = db.Column(db.Integer, ForeignKey('dogz.id', ondelete='CASCADE'), nullable=False)
    dog = relationship("Dogz", backref="bids", foreign_keys=[id_dog])
    initial_price = db.Column(db.Integer, nullable=True)
    last_price = db.Column(db.Integer, nullable=True)
    current_price = db.Column(db.Integer, nullable=False)
    sold = db.Column(db.Boolean, nullable=False)

    def __repr__(self):
        return f"Bidder(id_user = {self.id_user}, id_dog = {self.id_dog}, initial_price = {self.initial_price}, last_price = {self.last_price}, current_price = {self.current_price}, sold = {self.sold})"

models/dogs.py
from . import db
class Dogz(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    image = db.Column(db.String(100), nullable=False)
    breed = db.Column(db.String(100), nullable=False)
    aggression = db.Column(db.Integer, nullable=False)
    intel = db.Column(db.Integer, nullable=False)
    descrip = db.Column(db.String(100), nullable=False)

    def __repr__(self):
        return f"Dog(name = {self.name}, descrip = {self.descrip}, breed = {self.breed}, aggression = {self.aggression}, intel = {self.intel})"

models/users.py
from . import db
from datetime import datetime
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship


class Userz(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(200), nullable=False)
    password = db.Column(db.String(100), nullable=False)

    def __repr__(self):
        return {"name": self.name, "email": self.email}

website/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, DateField, BooleanField 
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email = StringField('Email',validators=[DataRequired(), Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    # def validate_username(self, username):
    #     user = User.query.filter_by(username=username.data).first()
    #     if user:
    #         raise ValidationError('That username is taken. Please choose a different one.')

class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(), Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    remember = BooleanField('Remember Me') 
    submit = SubmitField('Login')

main.py
from website import create_app
import secrets
app = create_app()
auth_key = secrets.token_hex(16)
app.config['SECRET_KEY'] = f"{auth_key}"

if __name__ == "__main__":
    app.run(port=8080, debug=True)

website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="")

    app.register_blueprint(auth, url_prefix="")

    # from ..models.engine import db

    return app

def create_database(app):
    pass

website/auth.py
from flask import Blueprint, render_template, request, url_for, redirect, flash    
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import RegistrationForm, LoginForm
import secrets

auth = Blueprint("auth", __name__, static_folder="static", template_folder="templates")

@auth.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('views.home'))
    return render_template("register.html", title='Register', form=form)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        flash(f'Welcome {form.email.data}!', 'success')
        return redirect(url_for('views.home'))
    return render_template("login.html", title='Login',form=form)

@auth.route("/logout")
def logout():
    return render_template("index.html")

website/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
import requests

BASE = "http://127.0.0.1:5000/api"
views = Blueprint("views", __name__, static_folder="static", template_folder="templates")

@views.route("/",  strict_slashes=False)
def home():
    response = requests.get(BASE + f"/dogs/") 
    dog_data = response.json()
    return render_template("index.html", dogs=dog_data)
    
@views.route("/bids",  strict_slashes=False)
def bids():
    response = requests.get(BASE + f"/dog/")
    bids_data = response.json()
    return render_template("bids.html", bids=bids_data)

templates/index.html
{% extends "base.html" %}

{% block body %}
        <main>
            <div class= "hero"> 
                <title> This Dog</title>    
            </div>
            <div class="lab">
                <h2>Hub</h2>
                <section class="s-lab">
		    {% for dog in dogs["dogs"] %}
                    	<article class=" art">
				<div class="title">
					<h1>{{ dog['name'] }}</h1>
					<h5>{{ dog['breed'] }}</h5>
				</div>
				<img src="{{ dog['image'] }}" alt="dog picture">
                        	<div class="descrip">
                          
			    		<p>Aggression level:{{ dog['aggression'] }} </p>
			    		<p>Intelligence level:{{ dog['intel'] }}</p>

				</div>
                        	<div class="checks">
                                	<div class="highlights1">
                                    		<div class = 'no'>No. of bids: 6</div>
                                    		<div class ='locss'>locations: 2</div>
                                    		<div class = 'hms'>Home Service: yes</div>
                                	</div>
                                </div>
				<div class="h-detail">
                                   <h1>Details: Husky are very beautiful dogs</h1>
                                </div>
                        	
                    </article>
		    {% endfor %} 
                </section>
            </div>
	</main>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% if title  %}
            <title>This Dog-{{ title }}</title>
        {% else  %}
            <title>This Dog</title>
        {% endif  %}

        <link rel="stylesheet" href="{{url_for('static', filename='css/body.css')}}">
        <link rel="icon" type="image/png" href="../images/icon.png">
    
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        {% block head %} 
        {% endblock %}
    </head>
    <body>
        <div class = "search">
            <section class ="s-search">
                <div class="details">
                    <div class="location">
                        <h3>Location</h3>
                        <h5>Lagos</h5>
                    </div>
                    <div class="request">
                        <h3>Breed</h3>
                        <h5>Husky</h5>
                    </div>
                </div>
                <button> SEARCH</button>
            </section>
        </div>
        {% with messages=get_flashed_messages(with_categories=true)  %}
            {% if messages  %}
                {% for category, message in messages  %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block body %}
        {% endblock %}

        <footer>
            <p>Keeper</p>
        </footer>   
    </body> 
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</html>

website/templates/bid.html
{% extends "base.html" %}

{% block body %}
        <main>
            <h1>make YOUR BID</h1>
            <form action="/" method="post">
                <input type="text" name="Price" id="price_id">

            </form>
        </main>

{% endblock %}

website/templates/bids.html
{% extends "base.html" %}

{% block body %}
        <main>
            <h1>Make YOUR BID</h1>
            {% if dog_id{{ dog_id }}: %}
            <h2>{{ dog_id }}</h2>
            <form action="/" method="post" class="needs-validation" novalidate>
                <div class="form-group">
                    <label for="price_id">Price</label>
                    <input type="text" name="Price" id="price_id" class="form-control" required>
                    <div class="invalid-feedback">
                        Please enter a valid price.
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </main>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block body %}
    <main>
		<div class="lab">
			<h2>Hub</h2>
			<section class="s-lab">
				{% for dog in dogs["dogs"] %}
				<article class="col-lg-4 col-md-6">
					<div class="title">
						<h3>{{ dog['name'] }}</h3>
						<h5>{{ dog['breed'] }}</h5>
					</div>
					<img src="{{ dog['image'] }}" alt="dog picture">
					<div class="checks">
						<div class="highlights1">
								<ul class='no'> Aggression level:{{ dog['aggression'] }} 
								</ul>
								<ul class='locss'> Intelligence level:{{ dog['intel'] }}</ul>
								<ul class='locss'> Description: {{ dog['descrip'] }}</ul>
						</div>
						<button class="m-2" onclick="window.location.href='http://127.0.0.1:8080/bids'">Make Bid
						</button>
					</div>
				</article>
		{% endfor %} 
			</section>
		</div>
	</main>
{% endblock %}

website/templates/login.html
<form>
    <!-- Email input -->
    <div class="form-outline mb-4">
      <input type="email" id="form2Example1" class="form-control" />
      <label class="form-label" for="form2Example1">Email address</label>
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
      <input type="password" id="form2Example2" class="form-control" />
      <label class="form-label" for="form2Example2">Password</label>
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <!-- Checkbox -->
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
          <label class="form-check-label" for="form2Example31"> Remember me </label>
        </div>
      </div>
  
      <div class="col">
        <!-- Simple link -->
        <a href="#!">Forgot password?</a>
      </div>
    </div>
  
    <!-- Submit button -->
    <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="#!">Register</a></p>
      <p>or sign up with:</p>
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-facebook-f"></i>
      </button>
  
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-google"></i>
      </button>
  
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-twitter"></i>
      </button>
  
      <button type="button" class="btn btn-link btn-floating mx-1">
        <i class="fab fa-github"></i>
      </button>
    </div>
  </form>

website/templates/register.html
{% extends "base.html" %}

    <title>Register</title>

{% block body %}
    <h2>Register</h2>
    <div class="content-section">
      <form action="" method="POST">
        {{ form.csrf_token }}
          <div>
            {{ form.username.label(class="form-control-label") }} 
            {% if form.username.errors %}
              {{form.username(class="form-control form-control-lg is-invalid")}}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>

          <div>
            {{ form.email.label(class="form-control-label") }} 
            {% if form.email.error %}
              {{form.email(class="form-control form-control-lg is-invalid")}}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>

          <div>
            {{ form.password.label(class="form-control-label") }} 
            {% if form.password.error %}
              {{form.password(class="form-control form-control-lg is-invalid")}}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>

          <div>
            {{ form.confirm_password.label(class="form-control-label") }} 
            {% if form.confirm_password.error %}
              {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
              <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.confirm_password(class="form-control form-control-lg") }}
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.submit (class="btn btn-outline-dark btn-lg") }}
          </div>
      </form>
    </div>
    <div class="border-top pt-1 text-center">
      <small class="text-muted">
      Already have an account? <a class="ml-2" href="{{ url_for('auth.login') }}">Sign in</a>
    </small>
    </div>
{% endblock body%}
```